// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "social.proto" (package "social", syntax proto3)
// tslint:disable
import { NotificationService } from "./social";
import type { Notification } from "./social";
import type { WatchRequest } from "./social";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { MarkAsReadRequest } from "./social";
import type { NotificationList } from "./social";
import type { ListNotificationsRequest } from "./social";
import { SocialService } from "./social";
import type { GetFollowingRequest } from "./social";
import type { GetFollowersRequest } from "./social";
import type { ToggleFollowResult } from "./social";
import type { ToggleFollowRequest } from "./social";
import { InteractionService } from "./social";
import type { CommentList } from "./social";
import type { ListCommentsRequest } from "./social";
import type { ListLikesResult } from "./social";
import type { ListLikesRequest } from "./social";
import type { DeleteCommentRequest } from "./social";
import type { CommentItem } from "./social";
import type { CommentRequest } from "./social";
import type { ToggleLikeResult } from "./social";
import type { ToggleLikeRequest } from "./social";
import { PostService } from "./social";
import type { ListUserPostsRequest } from "./social";
import type { PostList } from "./social";
import type { ListFeedRequest } from "./social";
import type { Empty } from "./social";
import type { DeletePostRequest } from "./social";
import type { GetPostRequest } from "./social";
import type { Post } from "./social";
import type { CreatePostRequest } from "./social";
import { AuthService } from "./social";
import type { DeleteUserResult } from "./social";
import type { DeleteUserRequest } from "./social";
import type { RefreshAccessTokenRequest } from "./social";
import type { LoginResult } from "./social";
import type { LoginRequest } from "./social";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserService } from "./social";
import type { UserList } from "./social";
import type { SearchUsersRequest } from "./social";
import type { UpdateProfileRequest } from "./social";
import type { GetUserByHandleRequest } from "./social";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { User } from "./social";
import type { GetUserByIdRequest } from "./social";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * --- SERVICES ---------------------------------------------
 *
 * @generated from protobuf service social.UserService
 */
export interface IUserServiceClient {
    /**
     * @generated from protobuf rpc: GetUserById
     */
    getUserById(input: GetUserByIdRequest, options?: RpcOptions): UnaryCall<GetUserByIdRequest, User>;
    /**
     * @generated from protobuf rpc: GetUserByHandle
     */
    getUserByHandle(input: GetUserByHandleRequest, options?: RpcOptions): UnaryCall<GetUserByHandleRequest, User>;
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, User>;
    /**
     * @generated from protobuf rpc: SearchUsers
     */
    searchUsers(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, UserList>;
}
/**
 * --- SERVICES ---------------------------------------------
 *
 * @generated from protobuf service social.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetUserById
     */
    getUserById(input: GetUserByIdRequest, options?: RpcOptions): UnaryCall<GetUserByIdRequest, User> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserByIdRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserByHandle
     */
    getUserByHandle(input: GetUserByHandleRequest, options?: RpcOptions): UnaryCall<GetUserByHandleRequest, User> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserByHandleRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, User> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateProfileRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchUsers
     */
    searchUsers(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, UserList> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchUsersRequest, UserList>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service social.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResult>;
    /**
     * @generated from protobuf rpc: RefreshAccessToken
     */
    refreshAccessToken(input: RefreshAccessTokenRequest, options?: RpcOptions): UnaryCall<RefreshAccessTokenRequest, LoginResult>;
    /**
     * @generated from protobuf rpc: DeleteUser
     */
    deleteUser(input: DeleteUserRequest, options?: RpcOptions): UnaryCall<DeleteUserRequest, DeleteUserResult>;
}
/**
 * @generated from protobuf service social.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshAccessToken
     */
    refreshAccessToken(input: RefreshAccessTokenRequest, options?: RpcOptions): UnaryCall<RefreshAccessTokenRequest, LoginResult> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshAccessTokenRequest, LoginResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteUser
     */
    deleteUser(input: DeleteUserRequest, options?: RpcOptions): UnaryCall<DeleteUserRequest, DeleteUserResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteUserRequest, DeleteUserResult>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service social.PostService
 */
export interface IPostServiceClient {
    /**
     * @generated from protobuf rpc: CreatePost
     */
    createPost(input: CreatePostRequest, options?: RpcOptions): UnaryCall<CreatePostRequest, Post>;
    /**
     * @generated from protobuf rpc: GetPost
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, Post>;
    /**
     * @generated from protobuf rpc: DeletePost
     */
    deletePost(input: DeletePostRequest, options?: RpcOptions): UnaryCall<DeletePostRequest, Empty>;
    /**
     * @generated from protobuf rpc: ListFeed
     */
    listFeed(input: ListFeedRequest, options?: RpcOptions): UnaryCall<ListFeedRequest, PostList>;
    /**
     * @generated from protobuf rpc: ListUserPosts
     */
    listUserPosts(input: ListUserPostsRequest, options?: RpcOptions): UnaryCall<ListUserPostsRequest, PostList>;
}
/**
 * @generated from protobuf service social.PostService
 */
export class PostServiceClient implements IPostServiceClient, ServiceInfo {
    typeName = PostService.typeName;
    methods = PostService.methods;
    options = PostService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePost
     */
    createPost(input: CreatePostRequest, options?: RpcOptions): UnaryCall<CreatePostRequest, Post> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePostRequest, Post>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPost
     */
    getPost(input: GetPostRequest, options?: RpcOptions): UnaryCall<GetPostRequest, Post> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostRequest, Post>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePost
     */
    deletePost(input: DeletePostRequest, options?: RpcOptions): UnaryCall<DeletePostRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePostRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFeed
     */
    listFeed(input: ListFeedRequest, options?: RpcOptions): UnaryCall<ListFeedRequest, PostList> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListFeedRequest, PostList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListUserPosts
     */
    listUserPosts(input: ListUserPostsRequest, options?: RpcOptions): UnaryCall<ListUserPostsRequest, PostList> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUserPostsRequest, PostList>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service social.InteractionService
 */
export interface IInteractionServiceClient {
    /**
     * @generated from protobuf rpc: ToggleLike
     */
    toggleLike(input: ToggleLikeRequest, options?: RpcOptions): UnaryCall<ToggleLikeRequest, ToggleLikeResult>;
    /**
     * @generated from protobuf rpc: AddComment
     */
    addComment(input: CommentRequest, options?: RpcOptions): UnaryCall<CommentRequest, CommentItem>;
    /**
     * @generated from protobuf rpc: DeleteComment
     */
    deleteComment(input: DeleteCommentRequest, options?: RpcOptions): UnaryCall<DeleteCommentRequest, Empty>;
    /**
     * @generated from protobuf rpc: ListLikes
     */
    listLikes(input: ListLikesRequest, options?: RpcOptions): UnaryCall<ListLikesRequest, ListLikesResult>;
    /**
     * @generated from protobuf rpc: ListComments
     */
    listComments(input: ListCommentsRequest, options?: RpcOptions): UnaryCall<ListCommentsRequest, CommentList>;
}
/**
 * @generated from protobuf service social.InteractionService
 */
export class InteractionServiceClient implements IInteractionServiceClient, ServiceInfo {
    typeName = InteractionService.typeName;
    methods = InteractionService.methods;
    options = InteractionService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ToggleLike
     */
    toggleLike(input: ToggleLikeRequest, options?: RpcOptions): UnaryCall<ToggleLikeRequest, ToggleLikeResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ToggleLikeRequest, ToggleLikeResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddComment
     */
    addComment(input: CommentRequest, options?: RpcOptions): UnaryCall<CommentRequest, CommentItem> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommentRequest, CommentItem>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteComment
     */
    deleteComment(input: DeleteCommentRequest, options?: RpcOptions): UnaryCall<DeleteCommentRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCommentRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListLikes
     */
    listLikes(input: ListLikesRequest, options?: RpcOptions): UnaryCall<ListLikesRequest, ListLikesResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListLikesRequest, ListLikesResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListComments
     */
    listComments(input: ListCommentsRequest, options?: RpcOptions): UnaryCall<ListCommentsRequest, CommentList> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCommentsRequest, CommentList>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service social.SocialService
 */
export interface ISocialServiceClient {
    /**
     * @generated from protobuf rpc: ToggleFollow
     */
    toggleFollow(input: ToggleFollowRequest, options?: RpcOptions): UnaryCall<ToggleFollowRequest, ToggleFollowResult>;
    /**
     * @generated from protobuf rpc: GetFollowers
     */
    getFollowers(input: GetFollowersRequest, options?: RpcOptions): UnaryCall<GetFollowersRequest, UserList>;
    /**
     * @generated from protobuf rpc: GetFollowing
     */
    getFollowing(input: GetFollowingRequest, options?: RpcOptions): UnaryCall<GetFollowingRequest, UserList>;
}
/**
 * @generated from protobuf service social.SocialService
 */
export class SocialServiceClient implements ISocialServiceClient, ServiceInfo {
    typeName = SocialService.typeName;
    methods = SocialService.methods;
    options = SocialService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ToggleFollow
     */
    toggleFollow(input: ToggleFollowRequest, options?: RpcOptions): UnaryCall<ToggleFollowRequest, ToggleFollowResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ToggleFollowRequest, ToggleFollowResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetFollowers
     */
    getFollowers(input: GetFollowersRequest, options?: RpcOptions): UnaryCall<GetFollowersRequest, UserList> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFollowersRequest, UserList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetFollowing
     */
    getFollowing(input: GetFollowingRequest, options?: RpcOptions): UnaryCall<GetFollowingRequest, UserList> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFollowingRequest, UserList>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service social.NotificationService
 */
export interface INotificationServiceClient {
    /**
     * @generated from protobuf rpc: ListNotifications
     */
    listNotifications(input: ListNotificationsRequest, options?: RpcOptions): UnaryCall<ListNotificationsRequest, NotificationList>;
    /**
     * @generated from protobuf rpc: MarkAsRead
     */
    markAsRead(input: MarkAsReadRequest, options?: RpcOptions): UnaryCall<MarkAsReadRequest, Empty>;
    /**
     * @generated from protobuf rpc: WatchNotifications
     */
    watchNotifications(input: WatchRequest, options?: RpcOptions): ServerStreamingCall<WatchRequest, Notification>;
}
/**
 * @generated from protobuf service social.NotificationService
 */
export class NotificationServiceClient implements INotificationServiceClient, ServiceInfo {
    typeName = NotificationService.typeName;
    methods = NotificationService.methods;
    options = NotificationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListNotifications
     */
    listNotifications(input: ListNotificationsRequest, options?: RpcOptions): UnaryCall<ListNotificationsRequest, NotificationList> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListNotificationsRequest, NotificationList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MarkAsRead
     */
    markAsRead(input: MarkAsReadRequest, options?: RpcOptions): UnaryCall<MarkAsReadRequest, Empty> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<MarkAsReadRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WatchNotifications
     */
    watchNotifications(input: WatchRequest, options?: RpcOptions): ServerStreamingCall<WatchRequest, Notification> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchRequest, Notification>("serverStreaming", this._transport, method, opt, input);
    }
}
